//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (1.4.0)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

import 'package:supabase_codegen/supabase_codegen.dart';
// Import enums if needed
// ignore: unused_import, always_use_package_imports
import '../database.dart';

/// Exercise Variants Table
class ExerciseVariantsTable extends SupabaseTable<ExerciseVariantsRow> {
  /// Table Name
  @override
  String get tableName => 'exercise_variants';

  /// Create a [ExerciseVariantsRow] from the [data] provided
  @override
  ExerciseVariantsRow createRow(Map<String, dynamic> data) =>
      ExerciseVariantsRow.fromJson(data);
}

/// Exercise Variants Row
class ExerciseVariantsRow extends SupabaseDataRow {
  /// Exercise Variants Row
  ExerciseVariantsRow({
    required String esercizioId,
    required String nomeVariante,
    String? variantId,
    String? descrizione,
    String? modifiche,
  }) : super({
          'esercizio_id': supaSerialize(esercizioId),
          'nome_variante': supaSerialize(nomeVariante),
          if (variantId != null) 'variant_id': supaSerialize(variantId),
          if (descrizione != null) 'descrizione': supaSerialize(descrizione),
          if (modifiche != null) 'modifiche': supaSerialize(modifiche),
        });

  /// Exercise Variants Row
  const ExerciseVariantsRow._(super.data);

  /// Create Exercise Variants Row from a [data] map
  factory ExerciseVariantsRow.fromJson(Map<String, dynamic> data) =>
      ExerciseVariantsRow._(data.cleaned);

  /// Get the Json representation of the row
  Map<String, dynamic> toJson() => data;

  /// Get the [SupabaseTable] for this row
  @override
  SupabaseTable get table => ExerciseVariantsTable();

  /// Variant Id field name
  static const String variantIdField = 'variant_id';

  /// Variant Id
  String get variantId => getField<String>(variantIdField, defaultValue: '')!;
  set variantId(String value) => setField<String>(variantIdField, value);

  /// Esercizio Id field name
  static const String esercizioIdField = 'esercizio_id';

  /// Esercizio Id
  String get esercizioId => getField<String>(esercizioIdField)!;
  set esercizioId(String value) => setField<String>(esercizioIdField, value);

  /// Nome Variante field name
  static const String nomeVarianteField = 'nome_variante';

  /// Nome Variante
  String get nomeVariante => getField<String>(nomeVarianteField)!;
  set nomeVariante(String value) => setField<String>(nomeVarianteField, value);

  /// Descrizione field name
  static const String descrizioneField = 'descrizione';

  /// Descrizione
  String? get descrizione => getField<String>(descrizioneField);
  set descrizione(String? value) => setField<String>(descrizioneField, value);

  /// Modifiche field name
  static const String modificheField = 'modifiche';

  /// Modifiche
  String? get modifiche => getField<String>(modificheField);
  set modifiche(String? value) => setField<String>(modificheField, value);

  /// Make a copy of the current [ExerciseVariantsRow]
  /// overriding the provided fields
  ExerciseVariantsRow copyWith({
    String? esercizioId,
    String? nomeVariante,
    String? variantId,
    String? descrizione,
    String? modifiche,
  }) =>
      ExerciseVariantsRow.fromJson({
        'esercizio_id': supaSerialize(esercizioId) ?? data['esercizio_id'],
        'nome_variante': supaSerialize(nomeVariante) ?? data['nome_variante'],
        'variant_id': supaSerialize(variantId) ?? data['variant_id'],
        'descrizione': supaSerialize(descrizione) ?? data['descrizione'],
        'modifiche': supaSerialize(modifiche) ?? data['modifiche'],
      });
}

/// Date: 2025-06-24 13:16:53.336486
