//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (1.4.0)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

import 'package:supabase_codegen/supabase_codegen.dart';
// Import enums if needed
// ignore: unused_import, always_use_package_imports
import '../database.dart';

/// Exercise Categories Table
class ExerciseCategoriesTable extends SupabaseTable<ExerciseCategoriesRow> {
  /// Table Name
  @override
  String get tableName => 'exercise_categories';

  /// Create a [ExerciseCategoriesRow] from the [data] provided
  @override
  ExerciseCategoriesRow createRow(Map<String, dynamic> data) =>
      ExerciseCategoriesRow.fromJson(data);
}

/// Exercise Categories Row
class ExerciseCategoriesRow extends SupabaseDataRow {
  /// Exercise Categories Row
  ExerciseCategoriesRow({
    required String nomeCategoria,
    String? categoriaId,
  }) : super({
          'nome_categoria': supaSerialize(nomeCategoria),
          if (categoriaId != null) 'categoria_id': supaSerialize(categoriaId),
        });

  /// Exercise Categories Row
  const ExerciseCategoriesRow._(super.data);

  /// Create Exercise Categories Row from a [data] map
  factory ExerciseCategoriesRow.fromJson(Map<String, dynamic> data) =>
      ExerciseCategoriesRow._(data.cleaned);

  /// Get the Json representation of the row
  Map<String, dynamic> toJson() => data;

  /// Get the [SupabaseTable] for this row
  @override
  SupabaseTable get table => ExerciseCategoriesTable();

  /// Categoria Id field name
  static const String categoriaIdField = 'categoria_id';

  /// Categoria Id
  String get categoriaId =>
      getField<String>(categoriaIdField, defaultValue: '')!;
  set categoriaId(String value) => setField<String>(categoriaIdField, value);

  /// Nome Categoria field name
  static const String nomeCategoriaField = 'nome_categoria';

  /// Nome Categoria
  String get nomeCategoria => getField<String>(nomeCategoriaField)!;
  set nomeCategoria(String value) =>
      setField<String>(nomeCategoriaField, value);

  /// Make a copy of the current [ExerciseCategoriesRow]
  /// overriding the provided fields
  ExerciseCategoriesRow copyWith({
    String? nomeCategoria,
    String? categoriaId,
  }) =>
      ExerciseCategoriesRow.fromJson({
        'nome_categoria':
            supaSerialize(nomeCategoria) ?? data['nome_categoria'],
        'categoria_id': supaSerialize(categoriaId) ?? data['categoria_id'],
      });
}

/// Date: 2025-06-24 13:16:53.332302
