//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (1.4.0)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

import 'package:supabase_codegen/supabase_codegen.dart';
// Import enums if needed
// ignore: unused_import, always_use_package_imports
import '../database.dart';

/// Goals Table
class GoalsTable extends SupabaseTable<GoalsRow> {
  /// Table Name
  @override
  String get tableName => 'goals';

  /// Create a [GoalsRow] from the [data] provided
  @override
  GoalsRow createRow(Map<String, dynamic> data) => GoalsRow.fromJson(data);
}

/// Goals Row
class GoalsRow extends SupabaseDataRow {
  /// Goals Row
  GoalsRow({
    required String userId,
    required String titolo,
    required GoalState stato,
    String? goalId,
    String? descrizione,
    DateTime? dataTarget,
    DateTime? dataCreazione,
  }) : super({
          'user_id': supaSerialize(userId),
          'titolo': supaSerialize(titolo),
          'stato': supaSerialize(stato),
          if (goalId != null) 'goal_id': supaSerialize(goalId),
          if (descrizione != null) 'descrizione': supaSerialize(descrizione),
          if (dataTarget != null) 'data_target': supaSerialize(dataTarget),
          if (dataCreazione != null)
            'data_creazione': supaSerialize(dataCreazione),
        });

  /// Goals Row
  const GoalsRow._(super.data);

  /// Create Goals Row from a [data] map
  factory GoalsRow.fromJson(Map<String, dynamic> data) =>
      GoalsRow._(data.cleaned);

  /// Get the Json representation of the row
  Map<String, dynamic> toJson() => data;

  /// Get the [SupabaseTable] for this row
  @override
  SupabaseTable get table => GoalsTable();

  /// Goal Id field name
  static const String goalIdField = 'goal_id';

  /// Goal Id
  String get goalId => getField<String>(goalIdField, defaultValue: '')!;
  set goalId(String value) => setField<String>(goalIdField, value);

  /// User Id field name
  static const String userIdField = 'user_id';

  /// User Id
  String get userId => getField<String>(userIdField)!;
  set userId(String value) => setField<String>(userIdField, value);

  /// Titolo field name
  static const String titoloField = 'titolo';

  /// Titolo
  String get titolo => getField<String>(titoloField)!;
  set titolo(String value) => setField<String>(titoloField, value);

  /// Descrizione field name
  static const String descrizioneField = 'descrizione';

  /// Descrizione
  String? get descrizione => getField<String>(descrizioneField);
  set descrizione(String? value) => setField<String>(descrizioneField, value);

  /// Data Target field name
  static const String dataTargetField = 'data_target';

  /// Data Target
  DateTime? get dataTarget => getField<DateTime>(dataTargetField);
  set dataTarget(DateTime? value) => setField<DateTime>(dataTargetField, value);

  /// Stato field name
  static const String statoField = 'stato';

  /// Stato
  GoalState get stato =>
      getField<GoalState>(statoField, enumValues: GoalState.values)!;
  set stato(GoalState value) => setField<GoalState>(statoField, value);

  /// Data Creazione field name
  static const String dataCreazioneField = 'data_creazione';

  /// Data Creazione
  DateTime get dataCreazione =>
      getField<DateTime>(dataCreazioneField, defaultValue: DateTime.now())!;
  set dataCreazione(DateTime value) =>
      setField<DateTime>(dataCreazioneField, value);

  /// Make a copy of the current [GoalsRow]
  /// overriding the provided fields
  GoalsRow copyWith({
    String? userId,
    String? titolo,
    GoalState? stato,
    String? goalId,
    String? descrizione,
    DateTime? dataTarget,
    DateTime? dataCreazione,
  }) =>
      GoalsRow.fromJson({
        'user_id': supaSerialize(userId) ?? data['user_id'],
        'titolo': supaSerialize(titolo) ?? data['titolo'],
        'stato': supaSerialize(stato) ?? data['stato'],
        'goal_id': supaSerialize(goalId) ?? data['goal_id'],
        'descrizione': supaSerialize(descrizione) ?? data['descrizione'],
        'data_target': supaSerialize(dataTarget) ?? data['data_target'],
        'data_creazione':
            supaSerialize(dataCreazione) ?? data['data_creazione'],
      });
}

/// Date: 2025-06-24 13:16:53.339853
