//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (1.4.0)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

import 'package:supabase_codegen/supabase_codegen.dart';
// Import enums if needed
// ignore: unused_import, always_use_package_imports
import '../database.dart';

/// Notifications Table
class NotificationsTable extends SupabaseTable<NotificationsRow> {
  /// Table Name
  @override
  String get tableName => 'notifications';

  /// Create a [NotificationsRow] from the [data] provided
  @override
  NotificationsRow createRow(Map<String, dynamic> data) =>
      NotificationsRow.fromJson(data);
}

/// Notifications Row
class NotificationsRow extends SupabaseDataRow {
  /// Notifications Row
  NotificationsRow({
    required String senderId,
    required String receiverId,
    required String messaggio,
    required NotificationType tipo,
    String? notificationId,
    DateTime? dataInvio,
    bool? letto,
  }) : super({
          'sender_id': supaSerialize(senderId),
          'receiver_id': supaSerialize(receiverId),
          'messaggio': supaSerialize(messaggio),
          'tipo': supaSerialize(tipo),
          if (notificationId != null)
            'notification_id': supaSerialize(notificationId),
          if (dataInvio != null) 'data_invio': supaSerialize(dataInvio),
          if (letto != null) 'letto': supaSerialize(letto),
        });

  /// Notifications Row
  const NotificationsRow._(super.data);

  /// Create Notifications Row from a [data] map
  factory NotificationsRow.fromJson(Map<String, dynamic> data) =>
      NotificationsRow._(data.cleaned);

  /// Get the Json representation of the row
  Map<String, dynamic> toJson() => data;

  /// Get the [SupabaseTable] for this row
  @override
  SupabaseTable get table => NotificationsTable();

  /// Notification Id field name
  static const String notificationIdField = 'notification_id';

  /// Notification Id
  String get notificationId =>
      getField<String>(notificationIdField, defaultValue: '')!;
  set notificationId(String value) =>
      setField<String>(notificationIdField, value);

  /// Sender Id field name
  static const String senderIdField = 'sender_id';

  /// Sender Id
  String get senderId => getField<String>(senderIdField)!;
  set senderId(String value) => setField<String>(senderIdField, value);

  /// Receiver Id field name
  static const String receiverIdField = 'receiver_id';

  /// Receiver Id
  String get receiverId => getField<String>(receiverIdField)!;
  set receiverId(String value) => setField<String>(receiverIdField, value);

  /// Messaggio field name
  static const String messaggioField = 'messaggio';

  /// Messaggio
  String get messaggio => getField<String>(messaggioField)!;
  set messaggio(String value) => setField<String>(messaggioField, value);

  /// Data Invio field name
  static const String dataInvioField = 'data_invio';

  /// Data Invio
  DateTime get dataInvio =>
      getField<DateTime>(dataInvioField, defaultValue: DateTime.now())!;
  set dataInvio(DateTime value) => setField<DateTime>(dataInvioField, value);

  /// Letto field name
  static const String lettoField = 'letto';

  /// Letto
  bool get letto => getField<bool>(lettoField, defaultValue: false)!;
  set letto(bool value) => setField<bool>(lettoField, value);

  /// Tipo field name
  static const String tipoField = 'tipo';

  /// Tipo
  NotificationType get tipo => getField<NotificationType>(tipoField,
      enumValues: NotificationType.values)!;
  set tipo(NotificationType value) =>
      setField<NotificationType>(tipoField, value);

  /// Make a copy of the current [NotificationsRow]
  /// overriding the provided fields
  NotificationsRow copyWith({
    String? senderId,
    String? receiverId,
    String? messaggio,
    NotificationType? tipo,
    String? notificationId,
    DateTime? dataInvio,
    bool? letto,
  }) =>
      NotificationsRow.fromJson({
        'sender_id': supaSerialize(senderId) ?? data['sender_id'],
        'receiver_id': supaSerialize(receiverId) ?? data['receiver_id'],
        'messaggio': supaSerialize(messaggio) ?? data['messaggio'],
        'tipo': supaSerialize(tipo) ?? data['tipo'],
        'notification_id':
            supaSerialize(notificationId) ?? data['notification_id'],
        'data_invio': supaSerialize(dataInvio) ?? data['data_invio'],
        'letto': supaSerialize(letto) ?? data['letto'],
      });
}

/// Date: 2025-06-24 13:16:53.343127
