//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (1.4.0)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

import 'package:supabase_codegen/supabase_codegen.dart';
// Import enums if needed
// ignore: unused_import, always_use_package_imports
import '../database.dart';

/// Onboarding Questions Table
class OnboardingQuestionsTable extends SupabaseTable<OnboardingQuestionsRow> {
  /// Table Name
  @override
  String get tableName => 'onboarding_questions';

  /// Create a [OnboardingQuestionsRow] from the [data] provided
  @override
  OnboardingQuestionsRow createRow(Map<String, dynamic> data) =>
      OnboardingQuestionsRow.fromJson(data);
}

/// Onboarding Questions Row
class OnboardingQuestionsRow extends SupabaseDataRow {
  /// Onboarding Questions Row
  OnboardingQuestionsRow({
    required String text,
    required Map<String, dynamic> options,
    required int step,
    int? id,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) : super({
          'text': supaSerialize(text),
          'options': supaSerialize(options),
          'step': supaSerialize(step),
          if (id != null) 'id': supaSerialize(id),
          if (createdAt != null) 'created_at': supaSerialize(createdAt),
          if (updatedAt != null) 'updated_at': supaSerialize(updatedAt),
        });

  /// Onboarding Questions Row
  const OnboardingQuestionsRow._(super.data);

  /// Create Onboarding Questions Row from a [data] map
  factory OnboardingQuestionsRow.fromJson(Map<String, dynamic> data) =>
      OnboardingQuestionsRow._(data.cleaned);

  /// Get the Json representation of the row
  Map<String, dynamic> toJson() => data;

  /// Get the [SupabaseTable] for this row
  @override
  SupabaseTable get table => OnboardingQuestionsTable();

  /// Id field name
  static const String idField = 'id';

  /// Id
  int? get id => getField<int?>(idField);
  set id(int? value) => setField<int?>(idField, value);

  /// Text field name
  static const String textField = 'text';

  /// Text
  String get text => getField<String>(textField)!;
  set text(String value) => setField<String>(textField, value);

  /// Options field name
  static const String optionsField = 'options';

  /// Options
  Map<String, dynamic> get options =>
      getField<Map<String, dynamic>>(optionsField)!;
  set options(Map<String, dynamic> value) =>
      setField<Map<String, dynamic>>(optionsField, value);

  /// Step field name
  static const String stepField = 'step';

  /// Step
  int get step => getField<int>(stepField)!;
  set step(int value) => setField<int>(stepField, value);

  /// Created At field name
  static const String createdAtField = 'created_at';

  /// Created At
  DateTime get createdAt =>
      getField<DateTime>(createdAtField, defaultValue: DateTime.now())!;
  set createdAt(DateTime value) => setField<DateTime>(createdAtField, value);

  /// Updated At field name
  static const String updatedAtField = 'updated_at';

  /// Updated At
  DateTime get updatedAt =>
      getField<DateTime>(updatedAtField, defaultValue: DateTime.now())!;
  set updatedAt(DateTime value) => setField<DateTime>(updatedAtField, value);

  /// Make a copy of the current [OnboardingQuestionsRow]
  /// overriding the provided fields
  OnboardingQuestionsRow copyWith({
    String? text,
    Map<String, dynamic>? options,
    int? step,
    int? id,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) =>
      OnboardingQuestionsRow.fromJson({
        'text': supaSerialize(text) ?? data['text'],
        'options': supaSerialize(options) ?? data['options'],
        'step': supaSerialize(step) ?? data['step'],
        'id': supaSerialize(id) ?? data['id'],
        'created_at': supaSerialize(createdAt) ?? data['created_at'],
        'updated_at': supaSerialize(updatedAt) ?? data['updated_at'],
      });
}

/// Date: 2025-06-24 13:16:53.347811
