//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (1.4.0)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

import 'package:supabase_codegen/supabase_codegen.dart';
// Import enums if needed
// ignore: unused_import, always_use_package_imports
import '../database.dart';

/// Onboardings Table
class OnboardingsTable extends SupabaseTable<OnboardingsRow> {
  /// Table Name
  @override
  String get tableName => 'onboardings';

  /// Create a [OnboardingsRow] from the [data] provided
  @override
  OnboardingsRow createRow(Map<String, dynamic> data) =>
      OnboardingsRow.fromJson(data);
}

/// Onboardings Row
class OnboardingsRow extends SupabaseDataRow {
  /// Onboardings Row
  OnboardingsRow({
    required String titolo,
    required String targetRoleId,
    String? onboardingId,
    String? ptId,
    String? clientId,
    String? stato,
    DateTime? dataCreazione,
    DateTime? dataPubblicazione,
    DateTime? dataCompletamento,
  }) : super({
          'titolo': supaSerialize(titolo),
          'target_role_id': supaSerialize(targetRoleId),
          if (onboardingId != null)
            'onboarding_id': supaSerialize(onboardingId),
          if (ptId != null) 'pt_id': supaSerialize(ptId),
          if (clientId != null) 'client_id': supaSerialize(clientId),
          if (stato != null) 'stato': supaSerialize(stato),
          if (dataCreazione != null)
            'data_creazione': supaSerialize(dataCreazione),
          if (dataPubblicazione != null)
            'data_pubblicazione': supaSerialize(dataPubblicazione),
          if (dataCompletamento != null)
            'data_completamento': supaSerialize(dataCompletamento),
        });

  /// Onboardings Row
  const OnboardingsRow._(super.data);

  /// Create Onboardings Row from a [data] map
  factory OnboardingsRow.fromJson(Map<String, dynamic> data) =>
      OnboardingsRow._(data.cleaned);

  /// Get the Json representation of the row
  Map<String, dynamic> toJson() => data;

  /// Get the [SupabaseTable] for this row
  @override
  SupabaseTable get table => OnboardingsTable();

  /// Onboarding Id field name
  static const String onboardingIdField = 'onboarding_id';

  /// Onboarding Id
  String get onboardingId =>
      getField<String>(onboardingIdField, defaultValue: '')!;
  set onboardingId(String value) => setField<String>(onboardingIdField, value);

  /// Pt Id field name
  static const String ptIdField = 'pt_id';

  /// Pt Id
  String? get ptId => getField<String>(ptIdField);
  set ptId(String? value) => setField<String>(ptIdField, value);

  /// Client Id field name
  static const String clientIdField = 'client_id';

  /// Client Id
  String? get clientId => getField<String>(clientIdField);
  set clientId(String? value) => setField<String>(clientIdField, value);

  /// Titolo field name
  static const String titoloField = 'titolo';

  /// Titolo
  String get titolo => getField<String>(titoloField)!;
  set titolo(String value) => setField<String>(titoloField, value);

  /// Target Role Id field name
  static const String targetRoleIdField = 'target_role_id';

  /// Target Role Id
  String get targetRoleId => getField<String>(targetRoleIdField)!;
  set targetRoleId(String value) => setField<String>(targetRoleIdField, value);

  /// Stato field name
  static const String statoField = 'stato';

  /// Stato
  String get stato => getField<String>(statoField, defaultValue: 'draft')!;
  set stato(String value) => setField<String>(statoField, value);

  /// Data Creazione field name
  static const String dataCreazioneField = 'data_creazione';

  /// Data Creazione
  DateTime get dataCreazione =>
      getField<DateTime>(dataCreazioneField, defaultValue: DateTime.now())!;
  set dataCreazione(DateTime value) =>
      setField<DateTime>(dataCreazioneField, value);

  /// Data Pubblicazione field name
  static const String dataPubblicazioneField = 'data_pubblicazione';

  /// Data Pubblicazione
  DateTime? get dataPubblicazione => getField<DateTime>(dataPubblicazioneField);
  set dataPubblicazione(DateTime? value) =>
      setField<DateTime>(dataPubblicazioneField, value);

  /// Data Completamento field name
  static const String dataCompletamentoField = 'data_completamento';

  /// Data Completamento
  DateTime? get dataCompletamento => getField<DateTime>(dataCompletamentoField);
  set dataCompletamento(DateTime? value) =>
      setField<DateTime>(dataCompletamentoField, value);

  /// Make a copy of the current [OnboardingsRow]
  /// overriding the provided fields
  OnboardingsRow copyWith({
    String? titolo,
    String? targetRoleId,
    String? onboardingId,
    String? ptId,
    String? clientId,
    String? stato,
    DateTime? dataCreazione,
    DateTime? dataPubblicazione,
    DateTime? dataCompletamento,
  }) =>
      OnboardingsRow.fromJson({
        'titolo': supaSerialize(titolo) ?? data['titolo'],
        'target_role_id': supaSerialize(targetRoleId) ?? data['target_role_id'],
        'onboarding_id': supaSerialize(onboardingId) ?? data['onboarding_id'],
        'pt_id': supaSerialize(ptId) ?? data['pt_id'],
        'client_id': supaSerialize(clientId) ?? data['client_id'],
        'stato': supaSerialize(stato) ?? data['stato'],
        'data_creazione':
            supaSerialize(dataCreazione) ?? data['data_creazione'],
        'data_pubblicazione':
            supaSerialize(dataPubblicazione) ?? data['data_pubblicazione'],
        'data_completamento':
            supaSerialize(dataCompletamento) ?? data['data_completamento'],
      });
}

/// Date: 2025-06-24 13:16:53.351028
