//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (1.4.0)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

import 'package:supabase_codegen/supabase_codegen.dart';
// Import enums if needed
// ignore: unused_import, always_use_package_imports
import '../database.dart';

/// Onboarding Items Table
class OnboardingItemsTable extends SupabaseTable<OnboardingItemsRow> {
  /// Table Name
  @override
  String get tableName => 'onboarding_items';

  /// Create a [OnboardingItemsRow] from the [data] provided
  @override
  OnboardingItemsRow createRow(Map<String, dynamic> data) =>
      OnboardingItemsRow.fromJson(data);
}

/// Onboarding Items Row
class OnboardingItemsRow extends SupabaseDataRow {
  /// Onboarding Items Row
  OnboardingItemsRow({
    required String onboardingId,
    required int questionId,
    int? passo,
    bool? obbligatoria,
  }) : super({
          'onboarding_id': supaSerialize(onboardingId),
          'question_id': supaSerialize(questionId),
          if (passo != null) 'passo': supaSerialize(passo),
          if (obbligatoria != null) 'obbligatoria': supaSerialize(obbligatoria),
        });

  /// Onboarding Items Row
  const OnboardingItemsRow._(super.data);

  /// Create Onboarding Items Row from a [data] map
  factory OnboardingItemsRow.fromJson(Map<String, dynamic> data) =>
      OnboardingItemsRow._(data.cleaned);

  /// Get the Json representation of the row
  Map<String, dynamic> toJson() => data;

  /// Get the [SupabaseTable] for this row
  @override
  SupabaseTable get table => OnboardingItemsTable();

  /// Onboarding Id field name
  static const String onboardingIdField = 'onboarding_id';

  /// Onboarding Id
  String get onboardingId => getField<String>(onboardingIdField)!;
  set onboardingId(String value) => setField<String>(onboardingIdField, value);

  /// Question Id field name
  static const String questionIdField = 'question_id';

  /// Question Id
  int get questionId => getField<int>(questionIdField)!;
  set questionId(int value) => setField<int>(questionIdField, value);

  /// Passo field name
  static const String passoField = 'passo';

  /// Passo
  int get passo => getField<int>(passoField, defaultValue: 1)!;
  set passo(int value) => setField<int>(passoField, value);

  /// Obbligatoria field name
  static const String obbligatoriaField = 'obbligatoria';

  /// Obbligatoria
  bool get obbligatoria =>
      getField<bool>(obbligatoriaField, defaultValue: true)!;
  set obbligatoria(bool value) => setField<bool>(obbligatoriaField, value);

  /// Make a copy of the current [OnboardingItemsRow]
  /// overriding the provided fields
  OnboardingItemsRow copyWith({
    String? onboardingId,
    int? questionId,
    int? passo,
    bool? obbligatoria,
  }) =>
      OnboardingItemsRow.fromJson({
        'onboarding_id': supaSerialize(onboardingId) ?? data['onboarding_id'],
        'question_id': supaSerialize(questionId) ?? data['question_id'],
        'passo': supaSerialize(passo) ?? data['passo'],
        'obbligatoria': supaSerialize(obbligatoria) ?? data['obbligatoria'],
      });
}

/// Date: 2025-06-24 13:16:53.345430
