//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (1.4.0)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

import 'package:supabase_codegen/supabase_codegen.dart';
// Import enums if needed
// ignore: unused_import, always_use_package_imports
import '../database.dart';

/// Onboarding Question Roles Table
class OnboardingQuestionRolesTable
    extends SupabaseTable<OnboardingQuestionRolesRow> {
  /// Table Name
  @override
  String get tableName => 'onboarding_question_roles';

  /// Create a [OnboardingQuestionRolesRow] from the [data] provided
  @override
  OnboardingQuestionRolesRow createRow(Map<String, dynamic> data) =>
      OnboardingQuestionRolesRow.fromJson(data);
}

/// Onboarding Question Roles Row
class OnboardingQuestionRolesRow extends SupabaseDataRow {
  /// Onboarding Question Roles Row
  OnboardingQuestionRolesRow({
    required int questionId,
    required String ruoloId,
  }) : super({
          'question_id': supaSerialize(questionId),
          'ruolo_id': supaSerialize(ruoloId),
        });

  /// Onboarding Question Roles Row
  const OnboardingQuestionRolesRow._(super.data);

  /// Create Onboarding Question Roles Row from a [data] map
  factory OnboardingQuestionRolesRow.fromJson(Map<String, dynamic> data) =>
      OnboardingQuestionRolesRow._(data.cleaned);

  /// Get the Json representation of the row
  Map<String, dynamic> toJson() => data;

  /// Get the [SupabaseTable] for this row
  @override
  SupabaseTable get table => OnboardingQuestionRolesTable();

  /// Question Id field name
  static const String questionIdField = 'question_id';

  /// Question Id
  int get questionId => getField<int>(questionIdField)!;
  set questionId(int value) => setField<int>(questionIdField, value);

  /// Ruolo Id field name
  static const String ruoloIdField = 'ruolo_id';

  /// Ruolo Id
  String get ruoloId => getField<String>(ruoloIdField)!;
  set ruoloId(String value) => setField<String>(ruoloIdField, value);

  /// Make a copy of the current [OnboardingQuestionRolesRow]
  /// overriding the provided fields
  OnboardingQuestionRolesRow copyWith({
    int? questionId,
    String? ruoloId,
  }) =>
      OnboardingQuestionRolesRow.fromJson({
        'question_id': supaSerialize(questionId) ?? data['question_id'],
        'ruolo_id': supaSerialize(ruoloId) ?? data['ruolo_id'],
      });
}

/// Date: 2025-06-24 13:16:53.346151
