//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (1.4.0)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

import 'package:supabase_codegen/supabase_codegen.dart';
// Import enums if needed
// ignore: unused_import, always_use_package_imports
import '../database.dart';

/// Pt Clients Table
class PtClientsTable extends SupabaseTable<PtClientsRow> {
  /// Table Name
  @override
  String get tableName => 'pt_clients';

  /// Create a [PtClientsRow] from the [data] provided
  @override
  PtClientsRow createRow(Map<String, dynamic> data) =>
      PtClientsRow.fromJson(data);
}

/// Pt Clients Row
class PtClientsRow extends SupabaseDataRow {
  /// Pt Clients Row
  PtClientsRow({
    required String ptId,
    required String clientId,
    required DateTime dataInizio,
    DateTime? dataFine,
    String? note,
  }) : super({
          'pt_id': supaSerialize(ptId),
          'client_id': supaSerialize(clientId),
          'data_inizio': supaSerialize(dataInizio),
          if (dataFine != null) 'data_fine': supaSerialize(dataFine),
          if (note != null) 'note': supaSerialize(note),
        });

  /// Pt Clients Row
  const PtClientsRow._(super.data);

  /// Create Pt Clients Row from a [data] map
  factory PtClientsRow.fromJson(Map<String, dynamic> data) =>
      PtClientsRow._(data.cleaned);

  /// Get the Json representation of the row
  Map<String, dynamic> toJson() => data;

  /// Get the [SupabaseTable] for this row
  @override
  SupabaseTable get table => PtClientsTable();

  /// Pt Id field name
  static const String ptIdField = 'pt_id';

  /// Pt Id
  String get ptId => getField<String>(ptIdField)!;
  set ptId(String value) => setField<String>(ptIdField, value);

  /// Client Id field name
  static const String clientIdField = 'client_id';

  /// Client Id
  String get clientId => getField<String>(clientIdField)!;
  set clientId(String value) => setField<String>(clientIdField, value);

  /// Data Inizio field name
  static const String dataInizioField = 'data_inizio';

  /// Data Inizio
  DateTime get dataInizio => getField<DateTime>(dataInizioField)!;
  set dataInizio(DateTime value) => setField<DateTime>(dataInizioField, value);

  /// Data Fine field name
  static const String dataFineField = 'data_fine';

  /// Data Fine
  DateTime? get dataFine => getField<DateTime>(dataFineField);
  set dataFine(DateTime? value) => setField<DateTime>(dataFineField, value);

  /// Note field name
  static const String noteField = 'note';

  /// Note
  String? get note => getField<String>(noteField);
  set note(String? value) => setField<String>(noteField, value);

  /// Make a copy of the current [PtClientsRow]
  /// overriding the provided fields
  PtClientsRow copyWith({
    String? ptId,
    String? clientId,
    DateTime? dataInizio,
    DateTime? dataFine,
    String? note,
  }) =>
      PtClientsRow.fromJson({
        'pt_id': supaSerialize(ptId) ?? data['pt_id'],
        'client_id': supaSerialize(clientId) ?? data['client_id'],
        'data_inizio': supaSerialize(dataInizio) ?? data['data_inizio'],
        'data_fine': supaSerialize(dataFine) ?? data['data_fine'],
        'note': supaSerialize(note) ?? data['note'],
      });
}

/// Date: 2025-06-24 13:16:53.354512
