//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (1.4.0)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

import 'package:supabase_codegen/supabase_codegen.dart';
// Import enums if needed
// ignore: unused_import, always_use_package_imports
import '../database.dart';

/// Roles Table
class RolesTable extends SupabaseTable<RolesRow> {
  /// Table Name
  @override
  String get tableName => 'roles';

  /// Create a [RolesRow] from the [data] provided
  @override
  RolesRow createRow(Map<String, dynamic> data) => RolesRow.fromJson(data);
}

/// Roles Row
class RolesRow extends SupabaseDataRow {
  /// Roles Row
  RolesRow({
    required String nomeRuolo,
    String? ruoloId,
  }) : super({
          'nome_ruolo': supaSerialize(nomeRuolo),
          if (ruoloId != null) 'ruolo_id': supaSerialize(ruoloId),
        });

  /// Roles Row
  const RolesRow._(super.data);

  /// Create Roles Row from a [data] map
  factory RolesRow.fromJson(Map<String, dynamic> data) =>
      RolesRow._(data.cleaned);

  /// Get the Json representation of the row
  Map<String, dynamic> toJson() => data;

  /// Get the [SupabaseTable] for this row
  @override
  SupabaseTable get table => RolesTable();

  /// Ruolo Id field name
  static const String ruoloIdField = 'ruolo_id';

  /// Ruolo Id
  String get ruoloId => getField<String>(ruoloIdField, defaultValue: '')!;
  set ruoloId(String value) => setField<String>(ruoloIdField, value);

  /// Nome Ruolo field name
  static const String nomeRuoloField = 'nome_ruolo';

  /// Nome Ruolo
  String get nomeRuolo => getField<String>(nomeRuoloField)!;
  set nomeRuolo(String value) => setField<String>(nomeRuoloField, value);

  /// Make a copy of the current [RolesRow]
  /// overriding the provided fields
  RolesRow copyWith({
    String? nomeRuolo,
    String? ruoloId,
  }) =>
      RolesRow.fromJson({
        'nome_ruolo': supaSerialize(nomeRuolo) ?? data['nome_ruolo'],
        'ruolo_id': supaSerialize(ruoloId) ?? data['ruolo_id'],
      });
}

/// Date: 2025-06-24 13:16:53.356243
