//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (1.4.0)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

import 'package:supabase_codegen/supabase_codegen.dart';
// Import enums if needed
// ignore: unused_import, always_use_package_imports
import '../database.dart';

/// Users Table
class UsersTable extends SupabaseTable<UsersRow> {
  /// Table Name
  @override
  String get tableName => 'users';

  /// Create a [UsersRow] from the [data] provided
  @override
  UsersRow createRow(Map<String, dynamic> data) => UsersRow.fromJson(data);
}

/// Users Row
class UsersRow extends SupabaseDataRow {
  /// Users Row
  UsersRow({
    required String nome,
    required String cognome,
    required String email,
    String? userId,
    String? firebaseUid,
    String? telefono,
    String? ruoloId,
    DateTime? dataCreazione,
    DateTime? dataAggiornamento,
    String? dataNascita,
    String? sesso,
    double? altezza,
    int? onboardingStep,
    bool? onboardingComplete,
    Map<String, dynamic>? onboardingData,
  }) : super({
          'nome': supaSerialize(nome),
          'cognome': supaSerialize(cognome),
          'email': supaSerialize(email),
          if (userId != null) 'user_id': supaSerialize(userId),
          if (firebaseUid != null) 'firebase_uid': supaSerialize(firebaseUid),
          if (telefono != null) 'telefono': supaSerialize(telefono),
          if (ruoloId != null) 'ruolo_id': supaSerialize(ruoloId),
          if (dataCreazione != null)
            'data_creazione': supaSerialize(dataCreazione),
          if (dataAggiornamento != null)
            'data_aggiornamento': supaSerialize(dataAggiornamento),
          if (dataNascita != null) 'data_nascita': supaSerialize(dataNascita),
          if (sesso != null) 'sesso': supaSerialize(sesso),
          if (altezza != null) 'altezza': supaSerialize(altezza),
          if (onboardingStep != null)
            'onboarding_step': supaSerialize(onboardingStep),
          if (onboardingComplete != null)
            'onboarding_complete': supaSerialize(onboardingComplete),
          if (onboardingData != null)
            'onboarding_data': supaSerialize(onboardingData),
        });

  /// Users Row
  const UsersRow._(super.data);

  /// Create Users Row from a [data] map
  factory UsersRow.fromJson(Map<String, dynamic> data) =>
      UsersRow._(data.cleaned);

  /// Get the Json representation of the row
  Map<String, dynamic> toJson() => data;

  /// Get the [SupabaseTable] for this row
  @override
  SupabaseTable get table => UsersTable();

  /// User Id field name
  static const String userIdField = 'user_id';

  /// User Id
  String get userId => getField<String>(userIdField, defaultValue: '')!;
  set userId(String value) => setField<String>(userIdField, value);

  /// Firebase Uid field name
  static const String firebaseUidField = 'firebase_uid';

  /// Firebase Uid
  String? get firebaseUid => getField<String>(firebaseUidField);
  set firebaseUid(String? value) => setField<String>(firebaseUidField, value);

  /// Nome field name
  static const String nomeField = 'nome';

  /// Nome
  String get nome => getField<String>(nomeField)!;
  set nome(String value) => setField<String>(nomeField, value);

  /// Cognome field name
  static const String cognomeField = 'cognome';

  /// Cognome
  String get cognome => getField<String>(cognomeField)!;
  set cognome(String value) => setField<String>(cognomeField, value);

  /// Email field name
  static const String emailField = 'email';

  /// Email
  String get email => getField<String>(emailField)!;
  set email(String value) => setField<String>(emailField, value);

  /// Telefono field name
  static const String telefonoField = 'telefono';

  /// Telefono
  String? get telefono => getField<String>(telefonoField);
  set telefono(String? value) => setField<String>(telefonoField, value);

  /// Ruolo Id field name
  static const String ruoloIdField = 'ruolo_id';

  /// Ruolo Id
  String? get ruoloId => getField<String>(ruoloIdField);
  set ruoloId(String? value) => setField<String>(ruoloIdField, value);

  /// Data Creazione field name
  static const String dataCreazioneField = 'data_creazione';

  /// Data Creazione
  DateTime get dataCreazione =>
      getField<DateTime>(dataCreazioneField, defaultValue: DateTime.now())!;
  set dataCreazione(DateTime value) =>
      setField<DateTime>(dataCreazioneField, value);

  /// Data Aggiornamento field name
  static const String dataAggiornamentoField = 'data_aggiornamento';

  /// Data Aggiornamento
  DateTime get dataAggiornamento =>
      getField<DateTime>(dataAggiornamentoField, defaultValue: DateTime.now())!;
  set dataAggiornamento(DateTime value) =>
      setField<DateTime>(dataAggiornamentoField, value);

  /// Data Nascita field name
  static const String dataNascitaField = 'data_nascita';

  /// Data Nascita
  String? get dataNascita => getField<String>(dataNascitaField);
  set dataNascita(String? value) => setField<String>(dataNascitaField, value);

  /// Sesso field name
  static const String sessoField = 'sesso';

  /// Sesso
  String? get sesso => getField<String>(sessoField);
  set sesso(String? value) => setField<String>(sessoField, value);

  /// Altezza field name
  static const String altezzaField = 'altezza';

  /// Altezza
  double? get altezza => getField<double>(altezzaField);
  set altezza(double? value) => setField<double>(altezzaField, value);

  /// Onboarding Step field name
  static const String onboardingStepField = 'onboarding_step';

  /// Onboarding Step
  int get onboardingStep =>
      getField<int>(onboardingStepField, defaultValue: 0)!;
  set onboardingStep(int value) => setField<int>(onboardingStepField, value);

  /// Onboarding Complete field name
  static const String onboardingCompleteField = 'onboarding_complete';

  /// Onboarding Complete
  bool get onboardingComplete =>
      getField<bool>(onboardingCompleteField, defaultValue: false)!;
  set onboardingComplete(bool value) =>
      setField<bool>(onboardingCompleteField, value);

  /// Onboarding Data field name
  static const String onboardingDataField = 'onboarding_data';

  /// Onboarding Data
  Map<String, dynamic>? get onboardingData =>
      getField<Map<String, dynamic>>(onboardingDataField);
  set onboardingData(Map<String, dynamic>? value) =>
      setField<Map<String, dynamic>>(onboardingDataField, value);

  /// Make a copy of the current [UsersRow]
  /// overriding the provided fields
  UsersRow copyWith({
    String? nome,
    String? cognome,
    String? email,
    String? userId,
    String? firebaseUid,
    String? telefono,
    String? ruoloId,
    DateTime? dataCreazione,
    DateTime? dataAggiornamento,
    String? dataNascita,
    String? sesso,
    double? altezza,
    int? onboardingStep,
    bool? onboardingComplete,
    Map<String, dynamic>? onboardingData,
  }) =>
      UsersRow.fromJson({
        'nome': supaSerialize(nome) ?? data['nome'],
        'cognome': supaSerialize(cognome) ?? data['cognome'],
        'email': supaSerialize(email) ?? data['email'],
        'user_id': supaSerialize(userId) ?? data['user_id'],
        'firebase_uid': supaSerialize(firebaseUid) ?? data['firebase_uid'],
        'telefono': supaSerialize(telefono) ?? data['telefono'],
        'ruolo_id': supaSerialize(ruoloId) ?? data['ruolo_id'],
        'data_creazione':
            supaSerialize(dataCreazione) ?? data['data_creazione'],
        'data_aggiornamento':
            supaSerialize(dataAggiornamento) ?? data['data_aggiornamento'],
        'data_nascita': supaSerialize(dataNascita) ?? data['data_nascita'],
        'sesso': supaSerialize(sesso) ?? data['sesso'],
        'altezza': supaSerialize(altezza) ?? data['altezza'],
        'onboarding_step':
            supaSerialize(onboardingStep) ?? data['onboarding_step'],
        'onboarding_complete':
            supaSerialize(onboardingComplete) ?? data['onboarding_complete'],
        'onboarding_data':
            supaSerialize(onboardingData) ?? data['onboarding_data'],
      });
}

/// Date: 2025-06-24 13:16:53.357747
