//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (1.4.0)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

/// Appointment Type enum
enum AppointmentType {
  /// virtuale
  virtuale,

  /// in_persona
  in_persona,
}

/// Date: 2025-06-24 13:16:53.304125
