//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (1.4.0)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

/// Appointment State enum
enum AppointmentState {
  /// scheduled
  scheduled,

  /// completed
  completed,

  /// canceled
  canceled,
}

/// Date: 2025-06-24 13:16:53.301445
