//
//  Generated file. Do not edit.
//  Generated by supabase_codegen (1.4.0)
//
// ignore_for_file: require_trailing_commas, constant_identifier_names

/// Notification Type enum
enum NotificationType {
  /// message
  message,

  /// reminder
  reminder,

  /// system
  system,
}

/// Date: 2025-06-24 13:16:53.304992
